"""
zara_scraper.py

Zara-specific implementation of BaseScraper.

Zara currently returns 403 to direct Python requests, while the public
website is accessible through a normal browser session. This scraper
therefore uses Playwright to load the Zara category page and captures
the product API response generated by the browser.

The rest of the application remains brand-agnostic.
"""

from typing import Optional, List

import pandas as pd
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

from base_scraper import BaseScraper, Product


class ZaraScraper(BaseScraper):
    brand_name = "Zara"

    def __init__(self, region_group_id: int = 8):
        self.region_group_id = region_group_id

    def fetch_catalogue(self, category_id: int) -> List[Product]:
        category_url = (
            f"https://www.zara.com/us/en/category/{category_id}/products"
            f"?regionGroupId={self.region_group_id}&ajax=true"
        )

        print(f"Opening Zara category: {category_url}")

        with sync_playwright() as p:
            # Start with a visible browser while debugging.
            # Once everything works, you can change this to headless=True.
            browser = p.chromium.launch(headless=False)

            context = browser.new_context(
                locale="en-US",
                viewport={"width": 1440, "height": 900},
            )

            page = context.new_page()

            product_data = None

            def capture_product_response(response):
                nonlocal product_data

                if "/products" not in response.url:
                    return

                if "regionGroupId=" not in response.url:
                    return

                try:
                    data = response.json()

                    if "productGroups" in data:
                        product_data = data
                        print(f"Captured Zara product API response:")
                        print(response.url)

                except Exception:
                    # Some responses may not be JSON.
                    pass

            page.on("response", capture_product_response)

            try:
                # First visit Zara homepage to establish a normal browser
                # session and obtain any cookies/session information.
                print("Opening Zara homepage...")
                page.goto(
                    "https://www.zara.com/us/en/",
                    wait_until="domcontentloaded",
                    timeout=60000,
                )

                # Give the page a moment to finish initial requests.
                page.wait_for_timeout(3000)

                print("Opening Zara category...")
                page.goto(
                    category_url,
                    wait_until="domcontentloaded",
                    timeout=60000,
                )

                # Allow API requests triggered by the page to complete.
                page.wait_for_timeout(5000)

            except PlaywrightTimeoutError as e:
                print(f"[warn] Zara page timed out: {e}")

            finally:
                browser.close()

        if product_data is None:
            print("Could not capture Zara product API response.")
            return []

        products: List[Product] = []

        for group in product_data.get("productGroups", []):
            for element in group.get("elements", []):
                for component in element.get("commercialComponents", []):
                    product = self._parse_component(component)

                    if product is not None:
                        products.append(product)

        print(f"Parsed {len(products)} Zara products.")

        self._rate_limit()

        return products

    def _parse_component(self, component: dict) -> Optional[Product]:
        name = component.get("name")
        product_id = component.get("id")

        seo = component.get("seo") or {}
        seo_slug = seo.get("keyword", "")

        product_url = (
            f"https://www.zara.com/us/en/{seo_slug}-p{product_id}.html"
            if product_id and seo_slug
            else None
        )

        sku = None

        if product_url:
            sku = product_url.split("-p")[-1].split(".html")[0]

        original = component.get("oldPrice")
        sale = component.get("price")
        discount_percent = component.get("displayDiscountPercentage")
        discount_label = component.get("discountLabel")

        detail = component.get("detail") or {}
        colors = detail.get("colors") or []

        images = []

        for color in colors:
            for media in color.get("xmedia", []):
                image_url = media.get("url", "").replace("{width}", "600")

                if image_url:
                    images.append(image_url)

        return Product(
            brand=self.brand_name,
            product_id=str(product_id) if product_id else None,
            sku=sku,
            name=name,
            original_price=original / 100 if original else None,
            sale_price=sale / 100 if sale else None,
            discount_percent=discount_percent,
            discount_label=discount_label,
            images=", ".join(images),
            url=product_url,
            scraped_at=pd.Timestamp.now(),
        )